# [Config] Base URL aplikasi yang akan di-test
baseUrl=https://www.qapractice.com/practice-ecommerece-website

# [Config] Browser yang digunakan
browser=chrome

# [Config] Jalankan browser tanpa tampilan GUI
headless=true

# [Config] Default explicit wait dalam detik
timeout=10